import { ArrowUpRight, Check, Clock3, ListTodo, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { taskApi } from '../services/api'

const formatDate = (value) => value ? new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric' }).format(new Date(value)) : 'No deadline'
export default function Dashboard() {
  const [tasks, setTasks] = useState([]); const [loading, setLoading] = useState(true)
  useEffect(() => { taskApi.list().then(({ data }) => setTasks(data)).finally(() => setLoading(false)) }, [])
  const pending = tasks.filter((task) => task.status !== 'completed'); const completed = tasks.length - pending.length; const dueSoon = pending.filter((task) => task.urgency === 'high' || task.urgency === 'critical')
  return <div className="page"><header className="page-header"><div><p className="eyebrow">THURSDAY, SEPTEMBER 18, 2026</p><h1>Good morning.</h1><p className="subtle">A clear view of what deserves your attention today.</p></div><Link className="icon-link" to="/tasks">View all tasks <ArrowUpRight size={16} /></Link></header><section className="digest-grid"><div className="digest-card"><div className="card-kicker"><Sparkles size={16} /> DAILY DIGEST</div><h2>{dueSoon.length ? `${dueSoon.length} ${dueSoon.length === 1 ? 'thing needs' : 'things need'} your attention.` : 'Your day has room to breathe.'}</h2><p>{dueSoon.length ? 'A quick pass now keeps the rest of the week light.' : 'No urgent tasks are waiting. Keep the momentum gentle.'}</p><Link to="/tasks" className="light-button">Plan my day <ArrowUpRight size={15} /></Link></div><div className="progress-card"><div className="card-kicker">WEEKLY PROGRESS</div><div className="progress-value">{tasks.length ? Math.round((completed / tasks.length) * 100) : 0}<span>%</span></div><div className="progress-bar"><span style={{ width: `${tasks.length ? (completed / tasks.length) * 100 : 0}%` }} /></div><p>{completed} of {tasks.length} tasks complete</p></div></section><section className="section-block"><div className="section-heading"><div><p className="eyebrow">UP NEXT</p><h2>Focus list</h2></div><Link to="/tasks" className="text-link">Manage list <ArrowUpRight size={14} /></Link></div>{loading ? <div className="empty-state">Loading your focus list...</div> : <div className="focus-list">{pending.slice(0, 4).map((task) => <div className="focus-row" key={task.id}><div className={`task-dot ${task.urgency}`}><Clock3 size={15} /></div><div className="focus-title"><strong>{task.title}</strong><span>{task.course_code || 'General'} · {formatDate(task.due_date)}</span></div><span className={`urgency ${task.urgency}`}>{task.urgency}</span></div>)}{!pending.length && <div className="empty-state">All caught up. Add your next academic move in Tasks.</div>}</div>}</section><section className="stat-strip"><div><ListTodo size={18} /><strong>{pending.length}</strong><span>open tasks</span></div><div><Check size={18} /><strong>{completed}</strong><span>completed</span></div><div><Clock3 size={18} /><strong>{dueSoon.length}</strong><span>due soon</span></div></section></div>
}
