import { CheckCircle2, ExternalLink, Mail, RefreshCw, ShieldCheck } from 'lucide-react'
import { useEffect, useState } from 'react'
import { emailApi, gmailApi } from '../services/api'

export default function Settings({ user }) {
  const [body, setBody] = useState(''); const [sender, setSender] = useState(''); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false); const [gmailConnected, setGmailConnected] = useState(false)
  useEffect(() => { gmailApi.status().then(({ data }) => setGmailConnected(data.connected)).catch(() => setGmailConnected(false)) }, [])
  const connectGmail = async () => { setStatus(''); try { const { data } = await gmailApi.authorize(); window.location.href = data.authorization_url } catch (error) { setStatus(error.response?.data?.detail || 'Google OAuth is not configured on the backend.') } }
  const syncGmail = async () => { setBusy(true); setStatus(''); try { const { data } = await gmailApi.sync(); setStatus(`${data.processed} emails checked; ${data.created_tasks.length} tasks created.`) } catch (error) { setStatus(error.response?.data?.detail || 'Gmail sync failed.') } finally { setBusy(false) } }
  const sync = async (event) => { event.preventDefault(); setBusy(true); setStatus(''); try { const { data } = await emailApi.sync([{ raw_body: body, sender }]); setStatus(`${data.created_tasks.length} task${data.created_tasks.length === 1 ? '' : 's'} created from this email.`); setBody(''); setSender('') } catch (error) { setStatus(error.response?.data?.detail || 'Sync failed. Check your API configuration.') } finally { setBusy(false) } }
  return <div className="page"><header className="page-header compact"><div><p className="eyebrow">WORKSPACE SETTINGS</p><h1>Settings.</h1><p className="subtle">Tune the handoff between your inbox and your plan.</p></div></header><section className="settings-grid"><div className="settings-main"><div className="setting-section"><div className="setting-heading"><div className="setting-icon"><Mail size={18} /></div><div><h2>Gmail inbox</h2><p>Connect Gmail with read-only permission to scan your academic messages.</p></div></div><div className="gmail-actions">{gmailConnected ? <><div className="connected-state"><CheckCircle2 size={17} /> Gmail connected</div><button className="primary-button" disabled={busy} onClick={syncGmail}><RefreshCw size={16} className={busy ? 'spin' : ''} />{busy ? 'Scanning inbox...' : 'Sync Gmail batch'}</button></> : <button className="primary-button" onClick={connectGmail}><ExternalLink size={16} /> Connect Gmail</button>}</div>{status && <p className={status.includes('created') || status.includes('checked') ? 'success-text' : 'error-text'}>{status}</p>}</div><div className="setting-section manual-section"><div className="setting-heading"><div className="setting-icon"><Mail size={18} /></div><div><h2>Manual email sync</h2><p>Paste one academic email when you do not want to connect Gmail.</p></div></div><form className="sync-form" onSubmit={sync}><label>Sender<input required value={sender} onChange={(event) => setSender(event.target.value)} placeholder="professor@university.edu" /></label><label>Email content<textarea required rows="7" value={body} onChange={(event) => setBody(event.target.value)} placeholder="Paste the full email here..." /></label><button className="primary-button" disabled={busy} type="submit"><RefreshCw size={16} className={busy ? 'spin' : ''} />{busy ? 'Reading email...' : 'Parse this email'}</button></form></div></div><aside className="settings-aside"><div className="account-card"><div className="avatar large">{user.email[0].toUpperCase()}</div><p className="eyebrow">SIGNED IN AS</p><strong>{user.email}</strong><div className="secure-line"><ShieldCheck size={15} /> Account protected</div></div><div className="setting-note"><p className="eyebrow">GMAIL PERMISSION</p><p>Google shows the consent screen. CampusFlow requests read-only Gmail access and never asks for or stores your Google password.</p></div></aside></section></div>
}
