import { Check, Filter, Plus, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { taskApi } from '../services/api'

const formatDate = (value) => value ? new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric' }).format(new Date(value)) : 'No date'
export default function Tasks() {
  const [tasks, setTasks] = useState([]); const [course, setCourse] = useState('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = () => taskApi.list().then(({ data }) => setTasks(data)).catch(() => setError('Could not load tasks.')).finally(() => setLoading(false))
  useEffect(() => { load() }, [])
  const toggle = async (task) => { const next = task.status === 'completed' ? 'pending' : 'completed'; setTasks((items) => items.map((item) => item.id === task.id ? { ...item, status: next } : item)); try { await taskApi.update(task.id, { status: next }) } catch { load() } }
  const remove = async (id) => { await taskApi.remove(id); setTasks((items) => items.filter((task) => task.id !== id)) }
  const courses = ['all', ...new Set(tasks.map((task) => task.course_code).filter(Boolean))]; const visible = tasks.filter((task) => course === 'all' || task.course_code === course)
  return <div className="page"><header className="page-header compact"><div><p className="eyebrow">TASKS / {tasks.length} TOTAL</p><h1>Your focus list.</h1><p className="subtle">Small, clear actions for a semester that moves forward.</p></div><button className="primary-button small-button"><Plus size={16} /> Add task</button></header><div className="toolbar"><div className="filter-label"><Filter size={15} /> FILTER BY COURSE</div><select value={course} onChange={(event) => setCourse(event.target.value)}>{courses.map((item) => <option key={item} value={item}>{item === 'all' ? 'All courses' : item}</option>)}</select></div>{error && <p className="error-text">{error}</p>}{loading ? <div className="empty-state">Loading tasks...</div> : <div className="task-list">{visible.map((task) => <div className={`task-card ${task.status === 'completed' ? 'is-complete' : ''}`} key={task.id}><button className="check-button" onClick={() => toggle(task)} aria-label={`Mark ${task.title} ${task.status === 'completed' ? 'pending' : 'complete'}`}>{task.status === 'completed' && <Check size={15} />}</button><div className="task-card-content"><strong>{task.title}</strong><p>{task.description || 'No additional notes.'}</p><div className="task-meta"><span>{task.course_code || 'General'}</span><span>{formatDate(task.due_date)}</span></div></div><span className={`urgency ${task.urgency}`}>{task.urgency}</span><button className="delete-button" onClick={() => remove(task.id)} aria-label={`Delete ${task.title}`}><Trash2 size={16} /></button></div>)}{!visible.length && <div className="empty-state">No tasks match this course filter.</div>}</div>}</div>
}
